default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123123123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: cleanify_development

test:
  <<: *default
  database: cleanify_test

production:
  <<: *default
  database: cleanify_production
  username: cleanify
  password: <%= ENV['CLEANIFY_DATABASE_PASSWORD'] %>
